### ISSUE TITLE
atsd container fails to start with error: ERROR zookeeper.ZooKeeperWatcher: hconnection Received unexpected KeeperException, re-throwing exception

### ISSUE THREAD

**Issue by demarant** [axibase/dockers#1] opened 2015-08-03 10:19 UTC
I just tried to run the atsd docker container by running the command exactly as described at
https://axibase.com/products/axibase-time-series-database/writing-data/docker-cadvisor/
since I would like to collect data from running docker containers.

The atsd container starts, but the application inside fails, as shown in the log tail below in this post.

Here is some info that may help you find the issue.

I am on a VM with ```CentOS Linux release 7.1.1503 (Core)```

docker version:
```
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): ba1f6c3/1.6.2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): ba1f6c3/1.6.2
OS/Arch (server): linux/amd64
```

docker info:
```
# docker info
Containers: 6
Images: 556
Storage Driver: devicemapper
 Pool Name: docker-253:2-258292-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: 
 Metadata file: 
 Data Space Used: 18.53 GB
 Data Space Total: 107.4 GB
 Data Space Available: 88.84 GB
 Metadata Space Used: 26.59 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.121 GB
 Udev Sync Supported: true
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Kernel Version: 3.10.0-229.7.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 3
Total Memory: 3.703 GiB
Name: swarm01
ID: YXBD:EZZA:32ZG:4ZQ4:PA6M:B6L4:DF2J:E3OH:OLQB:UJ3F:2OEN:RH2I
```

This is the result of tailing the start.log

docker exec -it atsd tail -f /opt/atsd/atsd/logs/start.log

```
15/08/03 10:02:50 ERROR zookeeper.ZooKeeperWatcher: hconnection Received unexpected KeeperException, re-throwing exception
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/hbaseid
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:1041)
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:172)
	at org.apache.hadoop.hbase.zookeeper.ZKUtil.checkExists(ZKUtil.java:450)
	at org.apache.hadoop.hbase.zookeeper.ClusterId.readClusterIdZNode(ClusterId.java:61)
	at org.apache.hadoop.hbase.zookeeper.ClusterId.getId(ClusterId.java:50)
	at org.apache.hadoop.hbase.zookeeper.ClusterId.hasId(ClusterId.java:44)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.ensureZookeeperTrackers(HConnectionManager.java:717)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.getMaster(HConnectionManager.java:786)
	at org.apache.hadoop.hbase.client.HBaseAdmin.<init>(HBaseAdmin.java:127)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:534)
	at org.jruby.javasupport.JavaConstructor.newInstanceDirect(JavaConstructor.java:275)
	at org.jruby.java.invokers.ConstructorInvoker.call(ConstructorInvoker.java:91)
	at org.jruby.java.invokers.ConstructorInvoker.call(ConstructorInvoker.java:178)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:322)
	at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:178)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:182)
	at org.jruby.java.proxies.ConcreteJavaProxy$2.call(ConcreteJavaProxy.java:47)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:322)
	at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:178)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:182)
	at org.jruby.RubyClass.newInstance(RubyClass.java:813)
	at org.jruby.RubyClass$i$newInstance.call(RubyClass$i$newInstance.gen:65535)
	at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroOrOneOrNBlock.call(JavaMethod.java:266)
	at org.jruby.java.proxies.ConcreteJavaProxy$3.call(ConcreteJavaProxy.java:143)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:312)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:169)
	at org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)
	at org.jruby.ast.InstAsgnNode.interpret(InstAsgnNode.java:95)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
	at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:75)
	at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:255)
	at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:203)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:342)
	at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:212)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:216)
	at org.jruby.RubyClass.newInstance(RubyClass.java:820)
	at org.jruby.RubyClass$i$newInstance.call(RubyClass$i$newInstance.gen:65535)
	at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroOrOneOrTwoOrNBlock.call(JavaMethod.java:283)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:332)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:203)
	at org.jruby.ast.CallTwoArgNode.interpret(CallTwoArgNode.java:59)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
	at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:75)
	at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:190)
	at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:179)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:312)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:169)
	at org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)
	at org.jruby.ast.InstAsgnNode.interpret(InstAsgnNode.java:95)
	at org.jruby.ast.OpAsgnOrNode.interpret(OpAsgnOrNode.java:100)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
	at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:75)
	at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:147)
	at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:163)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:292)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:135)
	at org.jruby.ast.CallNoArgNode.interpret(CallNoArgNode.java:63)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
	at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:75)
	at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:147)
	at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:163)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:292)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:135)
	at org.jruby.ast.VCallNode.interpret(VCallNode.java:86)
	at org.jruby.ast.CallNoArgNode.interpret(CallNoArgNode.java:63)
	at org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)
	at org.jruby.ast.LocalAsgnNode.interpret(LocalAsgnNode.java:123)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
	at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:75)
	at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:147)
	at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:163)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:292)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:135)
	at org.jruby.ast.FCallSpecialArgNode.interpret(FCallSpecialArgNode.java:37)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
	at org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
	at org.jruby.runtime.InterpretedBlock.evalBlockBody(InterpretedBlock.java:374)
	at org.jruby.runtime.InterpretedBlock.yield(InterpretedBlock.java:295)
	at org.jruby.runtime.InterpretedBlock.yieldSpecific(InterpretedBlock.java:229)
	at org.jruby.runtime.Block.yieldSpecific(Block.java:99)
	at org.jruby.ast.ZYieldNode.interpret(ZYieldNode.java:25)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
	at org.jruby.ast.RescueNode.executeBody(RescueNode.java:216)
	at org.jruby.ast.RescueNode.interpretWithJavaExceptions(RescueNode.java:120)
	at org.jruby.ast.RescueNode.interpret(RescueNode.java:110)
	at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:75)
	at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:169)
	at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:171)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:302)
	at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:144)
	at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:153)
	at org.jruby.ast.FCallSpecialArgBlockNode.interpret(FCallSpecialArgBlockNode.java:34)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
	at org.jruby.ast.RescueNode.executeBody(RescueNode.java:216)
	at org.jruby.ast.RescueNode.interpretWithJavaExceptions(RescueNode.java:120)
	at org.jruby.ast.RescueNode.interpret(RescueNode.java:110)
	at org.jruby.ast.EnsureNode.interpret(EnsureNode.java:96)
	at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:75)
	at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:190)
	at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:179)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:312)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:169)
	at org.jruby.ast.CallSpecialArgNode.interpret(CallSpecialArgNode.java:67)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
	at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:75)
	at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:190)
	at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:179)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:312)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:169)
	at org.jruby.ast.CallSpecialArgNode.interpret(CallSpecialArgNode.java:67)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
	at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:75)
	at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:147)
	at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:163)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:292)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:135)
	at org.jruby.ast.VCallNode.interpret(VCallNode.java:86)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
	at org.jruby.ast.RootNode.interpret(RootNode.java:129)
	at org.jruby.evaluator.ASTInterpreter.INTERPRET_EVAL(ASTInterpreter.java:96)
	at org.jruby.evaluator.ASTInterpreter.evalWithBinding(ASTInterpreter.java:161)
	at org.jruby.RubyKernel.evalCommon(RubyKernel.java:1135)
	at org.jruby.RubyKernel.eval(RubyKernel.java:1088)
	at org.jruby.RubyKernel$s$0$3$eval.call(RubyKernel$s$0$3$eval.gen:65535)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:181)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:282)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:71)
	at org.jruby.ast.FCallManyArgsNode.interpret(FCallManyArgsNode.java:60)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
	at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:75)
	at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:120)
	at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:134)
	at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:154)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:282)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:71)
	at org.jruby.ast.CallManyArgsNode.interpret(CallManyArgsNode.java:59)
	at org.jruby.ast.FCallOneArgNode.interpret(FCallOneArgNode.java:36)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
	at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:75)
	at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:233)
	at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:195)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:332)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:203)
	at org.jruby.ast.CallTwoArgNode.interpret(CallTwoArgNode.java:59)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
	at org.jruby.ast.RescueNode.executeBody(RescueNode.java:216)
	at org.jruby.ast.RescueNode.interpretWithJavaExceptions(RescueNode.java:120)
	at org.jruby.ast.RescueNode.interpret(RescueNode.java:110)
	at org.jruby.ast.BeginNode.interpret(BeginNode.java:83)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
	at org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
	at org.jruby.runtime.InterpretedBlock.evalBlockBody(InterpretedBlock.java:374)
	at org.jruby.runtime.InterpretedBlock.yield(InterpretedBlock.java:295)
	at org.jruby.runtime.InterpretedBlock.yieldSpecific(InterpretedBlock.java:229)
	at org.jruby.runtime.Block.yieldSpecific(Block.java:99)
	at org.jruby.ast.ZYieldNode.interpret(ZYieldNode.java:25)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
	at org.jruby.ast.EnsureNode.interpret(EnsureNode.java:96)
	at org.jruby.ast.BeginNode.interpret(BeginNode.java:83)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
	at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:75)
	at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:212)
	at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:187)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:322)
	at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:178)
	at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:187)
	at org.jruby.ast.FCallOneArgBlockNode.interpret(FCallOneArgBlockNode.java:34)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
	at org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
	at org.jruby.runtime.InterpretedBlock.evalBlockBody(InterpretedBlock.java:374)
	at org.jruby.runtime.InterpretedBlock.yieldSpecific(InterpretedBlock.java:260)
	at org.jruby.runtime.Block.yieldSpecific(Block.java:117)
	at org.jruby.ast.YieldTwoNode.interpret(YieldTwoNode.java:31)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
	at org.jruby.ast.IfNode.interpret(IfNode.java:117)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
	at org.jruby.ast.RescueNode.executeBody(RescueNode.java:216)
	at org.jruby.ast.RescueNode.interpretWithJavaExceptions(RescueNode.java:120)
	at org.jruby.ast.RescueNode.interpret(RescueNode.java:110)
	at org.jruby.ast.BeginNode.interpret(BeginNode.java:83)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
	at org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
	at org.jruby.runtime.InterpretedBlock.evalBlockBody(InterpretedBlock.java:374)
	at org.jruby.runtime.InterpretedBlock.yield(InterpretedBlock.java:295)
	at org.jruby.runtime.InterpretedBlock.yieldSpecific(InterpretedBlock.java:229)
	at org.jruby.runtime.Block.yieldSpecific(Block.java:99)
	at org.jruby.RubyKernel.loop(RubyKernel.java:1420)
	at org.jruby.RubyKernel$s$0$0$loop.call(RubyKernel$s$0$0$loop.gen:65535)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:302)
	at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:144)
	at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:153)
	at org.jruby.ast.FCallNoArgBlockNode.interpret(FCallNoArgBlockNode.java:32)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
	at org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
	at org.jruby.runtime.InterpretedBlock.evalBlockBody(InterpretedBlock.java:374)
	at org.jruby.runtime.InterpretedBlock.yield(InterpretedBlock.java:347)
	at org.jruby.runtime.InterpretedBlock.yield(InterpretedBlock.java:304)
	at org.jruby.runtime.Block.yield(Block.java:130)
	at org.jruby.RubyContinuation.enter(RubyContinuation.java:106)
	at org.jruby.RubyKernel.rbCatch(RubyKernel.java:1192)
	at org.jruby.RubyKernel$s$1$0$rbCatch.call(RubyKernel$s$1$0$rbCatch.gen:65535)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:322)
	at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:178)
	at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:187)
	at org.jruby.ast.FCallOneArgBlockNode.interpret(FCallOneArgBlockNode.java:34)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
	at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:75)
	at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:169)
	at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:171)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:302)
	at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:144)
	at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:153)
	at org.jruby.ast.CallNoArgBlockNode.interpret(CallNoArgBlockNode.java:64)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
	at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:75)
	at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:147)
	at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:163)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:292)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:135)
	at opt.atsd.hbase.bin.hirb.block_2$RUBY$start(/opt/atsd/hbase/bin/hirb.rb:183)
	at opt$atsd$hbase$bin$hirb$block_2$RUBY$start.call(opt$atsd$hbase$bin$hirb$block_2$RUBY$start:65535)
	at org.jruby.runtime.CompiledBlock.yield(CompiledBlock.java:112)
	at org.jruby.runtime.CompiledBlock.yield(CompiledBlock.java:95)
	at org.jruby.runtime.Block.yield(Block.java:130)
	at org.jruby.RubyContinuation.enter(RubyContinuation.java:106)
	at org.jruby.RubyKernel.rbCatch(RubyKernel.java:1192)
	at org.jruby.RubyKernel$s$1$0$rbCatch.call(RubyKernel$s$1$0$rbCatch.gen:65535)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:322)
	at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:178)
	at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:187)
	at opt.atsd.hbase.bin.hirb.method__5$RUBY$start(/opt/atsd/hbase/bin/hirb.rb:182)
	at opt$atsd$hbase$bin$hirb$method__5$RUBY$start.call(opt$atsd$hbase$bin$hirb$method__5$RUBY$start:65535)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:203)
	at org.jruby.internal.runtime.methods.CompiledMethod.call(CompiledMethod.java:255)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:292)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:135)
	at opt.atsd.hbase.bin.hirb.__file__(/opt/atsd/hbase/bin/hirb.rb:188)
	at opt.atsd.hbase.bin.hirb.load(/opt/atsd/hbase/bin/hirb.rb)
	at org.jruby.Ruby.runScript(Ruby.java:693)
	at org.jruby.Ruby.runScript(Ruby.java:686)
	at org.jruby.Ruby.runNormally(Ruby.java:593)
	at org.jruby.Ruby.runFromMain(Ruby.java:442)
	at org.jruby.Main.doRunFromMain(Main.java:321)
	at org.jruby.Main.internalRun(Main.java:241)
	at org.jruby.Main.run(Main.java:207)
	at org.jruby.Main.run(Main.java:191)
	at org.jruby.Main.main(Main.java:171)
 * [ATSD] HBase command timeout. Kill background processes ...
HBase Shell; enter 'help<RETURN>' for list of supported commands.
Type "exit<RETURN>" to leave the HBase Shell
Version 0.94.18, r1577788, Sat Mar 15 04:46:47 UTC 2014

list
TABLE
HBase Shell; enter 'help<RETURN>' for list of supported commands.
Type "exit<RETURN>" to leave the HBase Shell
Version 0.94.18, r1577788, Sat Mar 15 04:46:47 UTC 2014

list
TABLE
 * [ATSD] HBase Shell; enter 'help<RETURN>' for list of supported commands.
Type "exit<RETURN>" to leave the HBase Shell
Version 0.94.18, r1577788, Sat Mar 15 04:46:47 UTC 2014

list
TABLE
HBase Shell; enter 'help<RETURN>' for list of supported commands.
Type "exit<RETURN>" to leave the HBase Shell
Version 0.94.18, r1577788, Sat Mar 15 04:46:47 UTC 2014

list
TABLE
 * [ATSD] No corrupted files found in /hbase directory
 * [ATSD] WARNING: swap is missing.
 * [ATSD] All HBase processes are running, but shell test failed.
 * [ATSD] For more details see logfile in /opt/atsd/atsd/logs/start.log
```

it outputs the traceback above for each step during the startup.

Let me know if you need more debug info.

regards

**Comment by rodionos** [comment] 2015-08-03 10:32
Antonio, thanks for raising the issue. We'll replicate the issue on Centos 7 and will get back with our findings. Our internal docker installations are all running on Ubuntu 14 LTS.

**Comment by demarant** [comment] 2015-08-03 13:24
@rodionos thank you!
I confirm, I tried on my ubuntu 14.10 and it works. It seems actually related to CentOS or maybe more specifically to a specific kernel.
on Ubuntu 14.10 I run "3.16.0-41-generic"
on CentOS 7 I run "3.10.0-229.7.2.el7.x86_64"

so maybe it is because of the older kernel on CentOS 7...

**Comment by rodionos** [comment] 2015-08-03 14:22
Antonio, so far we tried the following on fresh CentOS installation but had no luck with reproducing the issue.

3.10.0-123.el7.x86_64 #1 SMP Mon Jun 30 12:09:22 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
3.10.0-229.7.2.el7.x86_64 #1 SMP Tue Jun 23 22:06:11 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Can you please attach the complete /opt/atsd/atsd/logs/start.log from the broken atsd/centos container.
Also, try restarting the container. If it fails to start (e.g. no UI on port 8088), start.log would be useful as well. Thanks again.

**Comment by demarant** [comment] 2015-08-04 14:17
@rodionos thanks
I tried again this morning and it just worked, than I stopped it and removed the container. I started it again and the issue appeared again, it is really weird, here is the [complete start.log as a gist](https://gist.github.com/demarant/623337f9587a82f04480)
it looks like a zookeeper issue

If I find something more I will report.

**Comment by demarant** [comment] 2015-08-04 14:39
I stopped and started again the atsd container and it went a bit better, the web UI at 8088 came up with a create user account (which I did not expect as I thought the user would be the one provided via thedocker run environment variables ATSD_USER_*  ...)
see the [second complete start.log gist](https://gist.github.com/demarant/040441007f7e8fb8c754#file-start-log-L10352)

**Comment by rodionos** [comment] 2015-08-04 15:01
We're trying to reproduce the problem in a setup without swap. We've had some issues before if swap is disabled. Hence the warning: [ATSD] WARNING: swap is missing.

**Comment by rodionos** [comment] 2015-08-04 15:40
No issues on CentOS without swap. Can you please attach /opt/atsd/install-sudo.log, /opt/atsd/install-user.log, /opt/atsd/hbase/logs/*, /opt/atsd/hadoop/logs/*, /opt/atsd/atsd/logs/*. By the way, is this VM running under VirtualBox or VMware?

**Comment by demarant** [comment] 2015-08-05 08:17
Thanks Rodionos.
In the mean time I can answer on the infrastructure. the CentOS 7 VM is created on www.cloudvps.com/ hosting provider running OpenStack. 
I created a new fresh VM and run again the atsd container and got same issues. So it is for me reproducible.
I will post all the logs as soon as I can.

**Comment by rodionos** [comment] 2015-08-05 10:16
We tried on AWS EC2 using the default CentOS 7 AMI ami-96a818fe. No issues. Looks like OpenStack issue, investigating...

**Comment by demarant** [comment] 2015-08-05 14:51
Hi,
here are [the log files](https://www.dropbox.com/s/o4hacbmycfi92ye/atsdlogs.tar.gz?dl=0)

**Comment by rodionos** [comment] 2015-08-05 16:42
We went ahead an rented a Centos 7 VPS on cloudvps, installed docker on it, but no luck again. We'll be reviewing logs tomorrow.

```
[root@vps64184 ~]# docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): ba1f6c3/1.6.2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): ba1f6c3/1.6.2
OS/Arch (server): linux/amd64

[root@vps64184 ~]# docker info
Containers: 1
Images: 17
Storage Driver: devicemapper
 Pool Name: docker-202:1-528842-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.001 GB
 Data Space Total: 107.4 GB
 Data Space Available: 39.41 GB
 Metadata Space Used: 1.634 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Kernel Version: 3.10.0-229.7.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 1
Total Memory: 808.6 MiB
Name: vps64184.public.cloudvps.com
ID: GVDU:ROO7:4O5D:6IGA:FYRV:GPB5:CXKT:OPPU:WOBR:77P6:FARD:L365
```

**Comment by rodionos** [comment] 2015-08-06 08:14
The logs show that there was a problem with HDFS on initial startup, subsequent restarts were ok. Could you please post /opt/atsd/hadoop/logs/* as well. Thanks.

**Comment by rodionos** [comment] 2015-08-06 08:16
Also, if you could attach output of `cat /etc/hosts` from this container, that would be great.

**Comment by demarant** [comment] 2015-08-06 14:37
[Hadoop logs](https://www.dropbox.com/s/c1y4gj8j4i9wyug/hadooplogs.tar.gz?dl=0)

```
# docker exec atsd cat /etc/hosts
172.17.0.9	atsd
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
```
:)

**Comment by rodionos** [comment] 2015-08-07 16:11
No hints in hadoop log. For some reason HDFS datanode Java process fails to start. Can you please remove the atsd image and re-launch it with other containers stopped. Just to eliminate memory shortage as one of the reasons.
 
docker rmi -f axibase/atsd

**Comment by rodionos** [comment] 2015-08-14 14:41
Could you please check if upgrading your docker daemon to 1.20 would solve the problem? We're not able to reproduce the issue on our end.

**Comment by rodionos** [comment] 2016-01-28 14:50
Closing the issue on wait t/o. Please re-open in case you run into the same issue on 1.9.1 and above.

**Closed by rodionos** 2016-01-28 14:50 UTC
